### ISSUE TITLE
About Snake gif

### ISSUE THREAD

**Issue by sleepymalc** [suliveevil/suliveevil#1]
Hi! When I'm randomly surfing in Github, I bumped into your personal page, and that Snake gif looks SICK! May I ask how you achieve this? Seems like you're using some script to keep your submissions record in sync with this gif?

**Comment by sleepymalc** [comment]
Ah-ha, I just figure it out! This looks really nice though! Appreciate it.

**Comment by suliveevil** [comment]
Have fun!
